
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE1_SOC_SDES(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/Wire declarations
//=======================================================
								  
	wire [7:0] Key1;
	wire [7:0] Key2;
	wire [7:0] Plaintext;
	wire [7:0] new_Plaintext;
	wire [7:0] Ciphertext;

//=======================================================
//  Structural coding
//=======================================================

	sdes_keygen (SW, Key1, Key2);
	sdes_encryption (Plaintext, Key1, Key2, Ciphertext);
	sdes_decryption (Ciphertext, Key1, Key2, new_Plaintext);
	
	bcd_to_sseg s0 (Key1[3:0], HEX0);
	bcd_to_sseg s1 (Key1[7:4], HEX1);
	bcd_to_sseg s2 (Key2[3:0], HEX2);
	bcd_to_sseg s3 (Key2[7:4], HEX3);
	
	assign LEDR = Ciphertext;
	assign Plaintext = 8'b01010101;
endmodule
